services:
  mcp-polygon:
    container_name: mcp-polygon
    runtime: runc
    build:
      context: backend
      dockerfile: Dockerfile.prod
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env.prod
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8006
      - TZ=UTC
      - MCP_NAME=polygon
    expose:
      - "8006"
    # restart: unless-stopped
    networks:
      - default
      - mcp-shared

networks:
  mcp-shared:
    external: true
